apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: trips
          image: registryknt1058.azurecr.io/trips:1.1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          env:
            - name: SQL_USER
              value: "sqladminkNt1058"
            - name: SQL_PASSWORD
              value: "qB8jp5Oj5"
            - name: SQL_SERVER
              value: "sqlserverknt1058.database.windows.net"
            - name: SQL_DBNAME
              value: "mydrivingDB"
            - name: DEBUG_LOGGING
              value: "true"
            - name: OPENAPI_DOCS_URI
              value: "http://localhost"
---
apiVersion: v1
kind: Service
metadata:
  name: trips
spec:
  ports:
    - port: 80
  selector:
    app: trips
