apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: userprofile
        image: registryknt1058.azurecr.io/userprofile:1.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: SQL_USER
          value: "sqladminkNt1058"
        - name: SQL_PASSWORD
          value: "qB8jp5Oj5"
        - name: SQL_SERVER
          value: "sqlserverknt1058.database.windows.net"
        - name:  SQL_DBNAME
          value: "mydrivingDB"
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
spec:
  ports:
  - port: 80
  selector:
    app: userprofile
